"""
Project: Project Euler - Problem 45: Triangular, Pentagonal, Hexagonal
Author: Mandeep Bhutani
Date: 3/31/2015

Problem: Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae: n(n+1)/2, n(3n-1)/2, n(2n-1). It can be verified that
T285 = P165 = H143 = 40755. Find the next triangle number that is also
pentagonal and hexagonal.
"""

triangular, pentagonal, hexagonal = [], [], []
for n in xrange(2, 100000):
    triangle = n * (n + 1) / 2
    pentagon = n * (3 * n - 1) / 2
    hexagon = n * (2 * n - 1)
    triangular.append(triangle)
    pentagonal.append(pentagon)
    hexagonal.append(hexagon)
result = [x for x in triangular if x in pentagonal if x in hexagonal]
print result
