"""
Project: Project Euler - Problem 45: Triangular, Pentagonal, Hexagonal
Author: Mandeep Bhutani
Date: 3/31/2015

Problem: Triangle, pentagonal, and hexagonal numbers are generated by the
following formulae: n(n+1)/2, n(3n-1)/2, n(2n-1). It can be verified that
T285 = P165 = H143 = 40755. Find the next triangle number that is also
pentagonal and hexagonal.
"""

triangle = [n * (n + 1) / 2 for n in xrange(1, 100000)]
pentagon = [n * (3 * n - 1) / 2 for n in xrange(1, 100000)]
hexagon = [n * (2 * n - 1) for n in xrange(1, 100000)]
for i in triangle:
    if i in pentagon and i in hexagon and i > 40755:
        print i
        break
