"""
Project: Project Euler - Problem 44: Pentagon Numbers
Author: Mandeep Bhutani
Date: 3/29/2015

Problem: Pentagonal numbers are generated by the formula, n*(3n -1)/2.The first
ten pentagon numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... It can
be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70  -22 = 48, is not pentagonal. Find the pair of pentagonal numbers, Pj and
Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is.
minimised; what is the value of D?

Description: A brute force method is used to check every value in a list of
pentagonal numbers.
"""
from math import fabs


def pentagonal(x):
    result = [n * (3 * n - 1) / 2 for n in xrange(1, x)]
    return result


total = pentagonal(4000)
for x in total:
    for y in total:
        if x + y in total and y - x in total:
            print int(fabs(y - x))
            break
