/**
* Title: Project Euler - Problem 2: Even Fibonacci Numbers
* Author: Mandeep Bhutani
* Date: 11/03/2017
* 
* Problem: Each new term in the Fibonacci sequence is generated by adding the
* previous two terms. By starting with 1 and 2, the first 10 terms will
* be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence
* whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <stdio.h>
#include <stdlib.h>


void swap(size_t *a, size_t *b) {
    size_t temp = *a;
    *a = *b;
    *b += temp;
}


int main(void) {
    size_t a = 0, b = 1;
    size_t summation = 0;

    while (a < 4000000) {
        if (a % 2 == 0) {
            summation += a;
        }
        swap(&a, &b);
    }
    printf("%zu\n", summation);
}
